# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-fastboot"
BBFILE_PATTERN_meta-fastboot = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-fastboot = "6"

LAYERDEPENDS_meta-fastboot = "core"
LAYERSERIES_COMPAT_meta-fastboot = "scarthgap"
