# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-iaca"
BBFILE_PATTERN_meta-iaca = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-iaca = "6"

LAYERDEPENDS:meta-iaca = "core meta-raspberrypi meta-openembedded/meta-oe"

LAYERSERIES_COMPAT_meta-iaca = "scarthgap"
